graphql:
  endpoint: "https://countries.trevorblades.com/graphql"

heatmap:
  query_type: "languages"
  row_field: "name"
  col_field: "rtl"
  row_label: "name"
  col_label: "rtl"
  value_scale: zscore
